//! Translation of `IMOD/3dmod/autox.cpp` together with `autox.h`.
//!
//! `autox.cpp` has file-static GUI/image state (`autoImage`, `autoWindow`,
//! and `sTopWin`).  [`AutoxState`] owns that state explicitly.  Operations in
//! IMOD's model, undo, image-processing, pyramid-cache, colour-ramp, and Qt
//! subsystems remain named calls on [`AutoxNativeBoundary`]; the flood-fill
//! state machine itself is native Rust and follows the source byte-for-byte.
#![allow(dead_code)]

pub const AUTOX_MAX_RESOLUTION: i32 = 200;
pub const AUTOX_FLOOD: u8 = 1;
pub const AUTOX_PATCH: u8 = 1 << 1;
pub const AUTOX_FILL: u8 = AUTOX_FLOOD | AUTOX_PATCH;
pub const AUTOX_BLACK: u8 = 1 << 2;
pub const AUTOX_WHITE: u8 = 1 << 3;
pub const AUTOX_CHECK: u8 = 1 << 5;
pub const AUTOX_ALL: u8 = 0xff;
pub const AUTOX_ALTMOUSE_DEFAULT: i32 = 0;
pub const AUTOX_ALTMOUSE_PAINT: i32 = 1;
pub const AUTOX_ALTMOUSE_DRAW: i32 = 2;

/// `AUTOX_OBJECT(x)`.
pub const fn autox_object(value: u8) -> u8 {
    value >> 4
}

/// `AUTOX_SET_OBJECT(x, o)`.
pub const fn autox_set_object(value: u8, object: u8) -> u8 {
    (value & (AUTOX_ALL >> 4)) | (object << 4)
}

/// `imod_autox_struct` (`autox.h`).  The C pointer to `ImodView` is an
/// argument to each Rust operation, avoiding an owning alias to the viewer.
#[derive(Clone, Debug, Default)]
pub struct Autox {
    pub data: Vec<u8>,
    pub byte_slice: Vec<u8>,
    pub shave: f64,
    pub threshold: i32,
    pub thresh_used: f32,
    pub reverse: i32,
    pub contrast: i32,
    pub filled: i32,
    pub cz: i32,
    pub altmouse: i32,
    pub xysize: usize,
    pub xlist: Vec<i32>,
    pub ylist: Vec<i32>,
    pub listsize: usize,
    pub diagonal: i32,
}

/// The `ViewInfo` fields read or written by this translation unit.
///
/// The desktop viewer bridges its actual `ImodView` into this source-shaped
/// representation for an Auto Contour action; it is deliberately not a
/// substitute display implementation.
#[derive(Clone, Debug, Default)]
pub struct AutoxView {
    pub xsize: i32,
    pub ysize: i32,
    pub zsize: i32,
    pub xysize: usize,
    pub xmouse: f32,
    pub ymouse: f32,
    pub zmouse: f32,
    pub insertmode: i32,
    pub ushort_store: i32,
    pub fake_image: i16,
    pub rampbase: i32,
    pub rampsize: i32,
    pub depth: i32,
    pub rgba: i32,
    pub black: i32,
    pub white: i32,
    pub threshold: i32,
}

/// Opaque contour generated by `imodContoursFromImagePoints`.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct AutoxContour {
    pub points: Vec<(f32, f32, f32)>,
}

/// File-static `autoImage`, `autoWindow`, and `sTopWin`.
#[derive(Clone, Debug, Default)]
pub struct AutoxState {
    pub auto_image: Vec<u8>,
    pub auto_window_open: bool,
    pub top_window_open: bool,
}

/// Calls outside `autox.cpp` made by the original source.
///
/// This is intentionally a direct boundary: implementations own real Qt
/// windows and the actual viewer/model, rather than emulating them here.
pub trait AutoxNativeBoundary {
    fn select_cramp_index(&mut self, index: i32);
    fn cramp_set_levels(&mut self, black: i32, white: i32);
    fn cramp_ramp(&mut self);
    fn cramp_get_levels(&mut self) -> (i32, i32);
    fn info_set_bw(&mut self, black: i32, white: i32);
    fn info_slider_to_level(&mut self, threshold: i32) -> i32;
    fn draw(&mut self, flags: i32);
    fn auto_patch(
        &mut self,
        data: &mut [u8],
        xlist: &mut [i32],
        ylist: &mut [i32],
        xsize: i32,
        ysize: i32,
    );
    fn auto_shrink(&mut self, data: &mut [u8], xsize: i32, ysize: i32);
    fn auto_expand(&mut self, data: &mut [u8], xsize: i32, ysize: i32);
    fn current_section(&mut self, z: i32, ushort_store: bool) -> Option<Vec<u8>>;
    fn model_has_object(&mut self) -> bool;
    fn contours_from_image_points(
        &mut self,
        data: &[u8],
        image: &[u8],
        xsize: i32,
        ysize: i32,
        z: i32,
        flags: u8,
        diagonal: i32,
        threshold: f32,
        reverse: i32,
    ) -> Vec<AutoxContour>;
    fn current_contour_surface(&mut self) -> i32;
    fn prepare_contour_for_autox(&mut self) -> bool;
    fn copy_autox_contour(&mut self, contour: &AutoxContour, surface: i32);
    fn set_new_contour_time(&mut self);
    fn contour_strip(&mut self);
    fn contour_reduce(&mut self, shave: f64);
    fn undo_finish_unit(&mut self);
    fn current_contour_center_of_mass(&mut self) -> Option<(f32, f32)>;
    fn iproc_busy(&mut self) -> bool;
    fn print(&mut self, text: &str);
    fn iproc_update(&mut self);
    fn iproc_call_when_free(&mut self);
    fn create_autox_window(&mut self) -> bool;
    fn raise_autox_window(&mut self);
    fn set_autox_window_states(
        &mut self,
        contrast: i32,
        threshold: i32,
        resolution: i32,
        altmouse: i32,
        diagonal: i32,
    );
    fn show_autox_window(&mut self);
    fn close_autox_window(&mut self);
    fn free_full_section(&mut self);
    fn cramp_selected_index(&mut self) -> i32;
}

/// `autoxSlider`.
pub fn autox_slider(
    ax: &mut Autox,
    which: i32,
    value: i32,
    view: &mut AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) {
    if which != 0 {
        ax.shave = value as f64 * 0.01;
    } else {
        ax.threshold = value;
        if ax.contrast != 0 {
            autox_contrast_selected(ax, 1, view, native);
        }
    }
}

/// `autoxContrastSelected`.
pub fn autox_contrast_selected(
    ax: &mut Autox,
    which: i32,
    view: &mut AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) {
    if ax.contrast != which {
        native.select_cramp_index(which);
    }
    ax.contrast = which;
    if which != 0 {
        if view.ushort_store != 0 {
            view.black = native.info_slider_to_level(ax.threshold);
            view.white = native.info_slider_to_level(ax.threshold + 1);
        } else {
            view.black = ax.threshold;
            view.white = ax.threshold + 1;
        }
        native.cramp_set_levels(view.black, view.white);
    } else {
        native.cramp_ramp();
        (view.black, view.white) = native.cramp_get_levels();
    }
    native.info_set_bw(view.black, view.white);
}

/// `autoxAltmouse`.
pub fn autox_altmouse(ax: &mut Autox, state: i32) {
    ax.altmouse = state;
}

/// `autoxFollowDiagonals`.
pub fn autox_follow_diagonals(ax: &mut Autox, state: i32) {
    ax.diagonal = state;
}

/// `autoxClosing`.
pub fn autox_closing(
    state: &mut AutoxState,
    ax: &mut Autox,
    view: &mut AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) {
    native.select_cramp_index(0);
    native.cramp_ramp();
    (view.black, view.white) = native.cramp_get_levels();
    view.threshold = ax.threshold;
    autox_clear(ax, AUTOX_ALL);
    native.info_set_bw(view.black, view.white);
    native.free_full_section();
    native.draw(1);
    ax.data.clear();
    ax.byte_slice.clear();
    ax.xlist.clear();
    ax.ylist.clear();
    state.auto_image.clear();
    state.auto_window_open = false;
    state.top_window_open = false;
    native.close_autox_window();
}

/// `autoxFill`.
pub fn autox_fill(
    state: &mut AutoxState,
    ax: &mut Autox,
    view: &mut AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) {
    if ax.cz as f32 == view.zmouse {
        autox_clear(ax, AUTOX_FILL);
    } else {
        autox_clear(ax, AUTOX_ALL);
    }
    autox_flood(state, ax, view, native);
    native.auto_patch(
        &mut ax.data,
        &mut ax.xlist,
        &mut ax.ylist,
        view.xsize,
        view.ysize,
    );
    ax.filled = 1;
    ax.cz = (view.zmouse + 0.5) as i32;
    native.draw(1);
}

/// `autoxBuild`.
pub fn autox_build_action(
    state: &mut AutoxState,
    ax: &mut Autox,
    view: &mut AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) {
    if ax.filled == 0 || !native.model_has_object() {
        return;
    }
    let Some(image) = native.current_section(ax.cz, view.ushort_store != 0) else {
        return;
    };
    state.auto_image = image;
    for point in &mut ax.data {
        if *point & AUTOX_BLACK != 0 {
            *point &= !AUTOX_FLOOD;
        }
    }
    let contours = native.contours_from_image_points(
        &ax.data,
        &state.auto_image,
        view.xsize,
        view.ysize,
        ax.cz,
        AUTOX_FLOOD | AUTOX_WHITE,
        ax.diagonal,
        ax.thresh_used,
        ax.reverse,
    );
    if contours.is_empty() {
        return;
    }
    for contour in &contours {
        let surface = native.current_contour_surface();
        if !native.prepare_contour_for_autox() {
            break;
        }
        native.copy_autox_contour(contour, surface);
        native.set_new_contour_time();
        native.contour_strip();
        if ax.shave > 0. {
            native.contour_reduce(ax.shave);
        }
    }
    autox_clear(ax, AUTOX_ALL);
    ax.filled = 0;
    native.undo_finish_unit();
    native.draw(1 | (1 << 1) | (1 << 2));
}

/// `autoxClear` (the source's public form action; distinct from static
/// `autox_clear`, which maps to the name below).
pub fn autox_clear_action(ax: &mut Autox, native: &mut dyn AutoxNativeBoundary) {
    autox_clear(ax, AUTOX_ALL);
    native.draw(1);
}

/// `autoxShrink`.
pub fn autox_shrink(ax: &mut Autox, view: &AutoxView, native: &mut dyn AutoxNativeBoundary) {
    native.auto_shrink(&mut ax.data, view.xsize, view.ysize);
    ax.thresh_used = -1.;
    native.draw(1);
}

/// `autoxExpand`.
pub fn autox_expand(ax: &mut Autox, view: &AutoxView, native: &mut dyn AutoxNativeBoundary) {
    native.auto_expand(&mut ax.data, view.xsize, view.ysize);
    native.auto_patch(
        &mut ax.data,
        &mut ax.xlist,
        &mut ax.ylist,
        view.xsize,
        view.ysize,
    );
    ax.thresh_used = -1.;
    native.draw(1);
}

/// `autoxSmooth`.
pub fn autox_smooth_action(ax: &mut Autox, view: &AutoxView, native: &mut dyn AutoxNativeBoundary) {
    native.auto_expand(&mut ax.data, view.xsize, view.ysize);
    native.auto_shrink(&mut ax.data, view.xsize, view.ysize);
    native.auto_patch(
        &mut ax.data,
        &mut ax.xlist,
        &mut ax.ylist,
        view.xsize,
        view.ysize,
    );
    ax.thresh_used = -1.;
    native.draw(1);
}

/// `autoxNext`.
pub fn autox_next_action(view: &mut AutoxView, native: &mut dyn AutoxNativeBoundary) {
    if native.iproc_busy() {
        native.print("\x07'Next' operation aborted because image processing is busy.\n");
        return;
    }
    if view.insertmode == 0 {
        if view.zmouse < (view.zsize - 1) as f32 {
            view.zmouse += 1.;
        }
    } else if view.zmouse > 0. {
        view.zmouse -= 1.;
    }
    native.iproc_update();
    native.iproc_call_when_free();
}

/// `continueNext`.
pub fn continue_next(
    state: &mut AutoxState,
    ax: &mut Autox,
    view: &mut AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) {
    let mut ci = 0.;
    let mut cj = 0.;
    let mut cp = 0.;
    for y in 0..view.ysize {
        for x in 0..view.xsize {
            if ax.data[(x + y * view.xsize) as usize] & AUTOX_FILL != 0 {
                ci += x as f32;
                cj += y as f32;
                cp += 1.;
            }
        }
    }
    if cp != 0. {
        view.xmouse = ci / cp;
        view.ymouse = cj / cp;
    } else if let Some((x, y)) = native.current_contour_center_of_mass() {
        view.xmouse = x;
        view.ymouse = y;
    }
    autox_fill(state, ax, view, native);
    native.draw(1 | (1 << 1));
}

/// `allocate_arrays`.
pub fn allocate_arrays(view: &AutoxView, ax: &mut Autox) -> i32 {
    let pixels = view.xysize;
    let listsize = 4usize
        .saturating_mul((view.xsize.max(0) as usize).saturating_add(view.ysize.max(0) as usize));
    let mut data = Vec::new();
    let mut xlist = Vec::new();
    let mut ylist = Vec::new();
    let mut byte_slice = Vec::new();
    if data.try_reserve_exact(pixels).is_err()
        || xlist.try_reserve_exact(listsize).is_err()
        || ylist.try_reserve_exact(listsize).is_err()
        || (view.ushort_store != 0 && byte_slice.try_reserve_exact(pixels).is_err())
    {
        return -1;
    }
    data.resize(pixels, 0);
    xlist.resize(listsize, 0);
    ylist.resize(listsize, 0);
    if view.ushort_store != 0 {
        byte_slice.resize(pixels, 0);
    }
    ax.data = data;
    ax.xlist = xlist;
    ax.ylist = ylist;
    ax.byte_slice = byte_slice;
    ax.xysize = pixels;
    ax.listsize = listsize;
    0
}

/// `autox_newsize`.
pub fn autox_newsize(view: &AutoxView, ax: &mut Autox, native: &mut dyn AutoxNativeBoundary) {
    ax.data.clear();
    ax.xlist.clear();
    ax.ylist.clear();
    ax.byte_slice.clear();
    if allocate_arrays(view, ax) != 0 {
        native.print("\x07AutoContour failed to get new image memory.");
        native.close_autox_window();
    } else {
        autox_clear(ax, AUTOX_ALL);
    }
    ax.filled = 0;
}

/// `autox_open`.
pub fn autox_open(
    state: &mut AutoxState,
    view: &AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) -> Option<Autox> {
    if view.fake_image != 0 {
        native.print("\x07AutoContour cannot be used with no image.");
        return None;
    }
    if state.auto_window_open {
        native.raise_autox_window();
        return None;
    }
    if !native.create_autox_window() {
        native.print("AutoContour Open failed: No window available.");
        return None;
    }
    let mut ax = Autox {
        threshold: view.threshold,
        contrast: 0,
        reverse: 0,
        shave: 0.25,
        filled: 0,
        altmouse: 0,
        cz: (view.zmouse + 0.5) as i32,
        diagonal: 0,
        ..Default::default()
    };
    if allocate_arrays(view, &mut ax) != 0 {
        native.close_autox_window();
        native.print("AutoContour Open failed: No memory.");
        return None;
    }
    native.set_autox_window_states(
        ax.contrast,
        ax.threshold,
        (100. * ax.shave) as i32,
        ax.altmouse,
        ax.diagonal,
    );
    autox_clear(&mut ax, AUTOX_ALL);
    state.auto_window_open = true;
    state.top_window_open = true;
    native.show_autox_window();
    Some(ax)
}

/// `autoxCrampSelected`.
pub fn autox_cramp_selected(ax: Option<&mut Autox>, native: &mut dyn AutoxNativeBoundary) {
    let Some(ax) = ax else {
        return;
    };
    ax.contrast = if native.cramp_selected_index() == 1 {
        1
    } else {
        0
    };
    native.set_autox_window_states(
        ax.contrast,
        ax.threshold,
        (100. * ax.shave) as i32,
        ax.altmouse,
        ax.diagonal,
    );
}

/// `autox_setlow`.
pub fn autox_setlow(
    ax: &mut Autox,
    view: &AutoxView,
    x: i32,
    y: i32,
    native: &mut dyn AutoxNativeBoundary,
) -> i32 {
    if x < 0 || y < 0 || x >= view.xsize || y >= view.ysize {
        return 1;
    }
    let point = &mut ax.data[(x + y * view.xsize) as usize];
    *point &= !AUTOX_WHITE;
    *point |= AUTOX_BLACK;
    ax.filled = 1;
    native.draw(1);
    0
}

/// `autox_sethigh`.
pub fn autox_sethigh(
    ax: &mut Autox,
    view: &AutoxView,
    x: i32,
    y: i32,
    native: &mut dyn AutoxNativeBoundary,
) -> i32 {
    if x < 0 || y < 0 || x >= view.xsize || y >= view.ysize {
        return 1;
    }
    let point = &mut ax.data[(x + y * view.xsize) as usize];
    *point &= !AUTOX_BLACK;
    *point |= AUTOX_WHITE;
    ax.filled = 1;
    native.draw(1);
    0
}

/// `autox_fillmouse`.
pub fn autox_fillmouse(
    state: &mut AutoxState,
    ax: &mut Autox,
    view: &mut AutoxView,
    xm: i32,
    ym: i32,
    native: &mut dyn AutoxNativeBoundary,
) -> i32 {
    view.xmouse = xm as f32;
    view.ymouse = ym as f32;
    autox_fill(state, ax, view, native);
    0
}

/// `autox_build` (the externally callable wrapper, not `autoxBuild`).
pub fn autox_build(
    state: &mut AutoxState,
    ax: Option<&mut Autox>,
    view: &mut AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) -> i32 {
    let Some(ax) = ax else {
        return -1;
    };
    autox_build_action(state, ax, view, native);
    0
}
/// `autox_next` (the externally callable wrapper, not `autoxNext`).
pub fn autox_next(
    ax: Option<&Autox>,
    view: &mut AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) -> i32 {
    if ax.is_none() {
        -1
    } else {
        autox_next_action(view, native);
        0
    }
}
/// `autox_smooth` (the externally callable wrapper, not `autoxSmooth`).
pub fn autox_smooth(
    ax: Option<&mut Autox>,
    view: &AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) -> i32 {
    let Some(ax) = ax else {
        return -1;
    };
    autox_smooth_action(ax, view, native);
    0
}

/// `autox_flood`.
pub fn autox_flood(
    state: &mut AutoxState,
    ax: &mut Autox,
    view: &AutoxView,
    native: &mut dyn AutoxNativeBoundary,
) -> i32 {
    let section = native.current_section(view.zmouse.round() as i32, view.ushort_store != 0);
    let Some(image) = section else {
        return 0;
    };
    state.auto_image = image;
    if state.auto_image.len() < view.xysize || ax.data.len() < view.xysize || ax.listsize == 0 {
        return 0;
    }
    let mut x = view.xmouse as i32;
    let mut y = view.ymouse as i32;
    if x < 0 || y < 0 || x >= view.xsize || y >= view.ysize {
        return 0;
    }
    let mut threshold = ax.threshold + 1;
    if view.depth == 8 && view.rgba == 0 {
        threshold =
            ((view.rampsize as f32 / 256. * threshold as f32) + view.rampbase as f32) as i32;
    }
    ax.thresh_used = threshold as f32 - 0.5;
    let index = (x + y * view.xsize) as usize;
    ax.reverse = i32::from((state.auto_image[index] as i32) < threshold);
    ax.xlist[0] = x;
    ax.ylist[0] = y;
    ax.data[index] |= AUTOX_CHECK;
    let mut ringnext = 0usize;
    let mut ringfree = 1usize;
    let neighflag = AUTOX_FLOOD | AUTOX_CHECK;
    while ringnext != ringfree {
        x = ax.xlist[ringnext];
        y = ax.ylist[ringnext];
        let point = (x + y * view.xsize) as usize;
        let test = if ax.reverse != 0 {
            (state.auto_image[point] as i32) < threshold || ax.data[point] & AUTOX_BLACK != 0
        } else {
            (state.auto_image[point] as i32 >= threshold || ax.data[point] & AUTOX_WHITE != 0)
                && ax.data[point] & AUTOX_BLACK == 0
        };
        if test {
            ax.data[point] |= AUTOX_FLOOD;
            if x > 0 && ax.data[point - 1] & neighflag == 0 {
                ax.xlist[ringfree] = x - 1;
                ax.ylist[ringfree] = y;
                ringfree = (ringfree + 1) % ax.listsize;
                ax.data[point - 1] |= AUTOX_CHECK;
            }
            if x < view.xsize - 1 && ax.data[point + 1] & neighflag == 0 {
                ax.xlist[ringfree] = x + 1;
                ax.ylist[ringfree] = y;
                ringfree = (ringfree + 1) % ax.listsize;
                ax.data[point + 1] |= AUTOX_CHECK;
            }
            if y > 0 && ax.data[point - view.xsize as usize] & neighflag == 0 {
                ax.xlist[ringfree] = x;
                ax.ylist[ringfree] = y - 1;
                ringfree = (ringfree + 1) % ax.listsize;
                ax.data[point - view.xsize as usize] |= AUTOX_CHECK;
            }
            if y < view.ysize - 1 && ax.data[point + view.xsize as usize] & neighflag == 0 {
                ax.xlist[ringfree] = x;
                ax.ylist[ringfree] = y + 1;
                ringfree = (ringfree + 1) % ax.listsize;
                ax.data[point + view.xsize as usize] |= AUTOX_CHECK;
            }
            if ax.diagonal != 0 {
                if x > 0 && y > 0 && ax.data[point - 1 - view.xsize as usize] & neighflag == 0 {
                    ax.xlist[ringfree] = x - 1;
                    ax.ylist[ringfree] = y - 1;
                    ringfree = (ringfree + 1) % ax.listsize;
                    ax.data[point - 1 - view.xsize as usize] |= AUTOX_CHECK;
                }
                if x < view.xsize - 1
                    && y > 0
                    && ax.data[point + 1 - view.xsize as usize] & neighflag == 0
                {
                    ax.xlist[ringfree] = x + 1;
                    ax.ylist[ringfree] = y - 1;
                    ringfree = (ringfree + 1) % ax.listsize;
                    ax.data[point + 1 - view.xsize as usize] |= AUTOX_CHECK;
                }
                if x > 0
                    && y < view.ysize - 1
                    && ax.data[point - 1 + view.xsize as usize] & neighflag == 0
                {
                    ax.xlist[ringfree] = x - 1;
                    ax.ylist[ringfree] = y + 1;
                    ringfree = (ringfree + 1) % ax.listsize;
                    ax.data[point - 1 + view.xsize as usize] |= AUTOX_CHECK;
                }
                if x < view.xsize - 1
                    && y < view.ysize - 1
                    && ax.data[point + 1 + view.xsize as usize] & neighflag == 0
                {
                    ax.xlist[ringfree] = x + 1;
                    ax.ylist[ringfree] = y + 1;
                    ringfree = (ringfree + 1) % ax.listsize;
                    ax.data[point + 1 + view.xsize as usize] |= AUTOX_CHECK;
                }
            }
        }
        ax.data[point] &= !AUTOX_CHECK;
        ringnext = (ringnext + 1) % ax.listsize;
    }
    1
}

/// `autox_clear`.
pub fn autox_clear(ax: &mut Autox, bit: u8) {
    for point in &mut ax.data {
        *point &= !bit;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[derive(Default)]
    struct Native {
        image: Vec<u8>,
        calls: Vec<String>,
        busy: bool,
    }
    impl AutoxNativeBoundary for Native {
        fn select_cramp_index(&mut self, n: i32) {
            self.calls.push(format!("select:{n}"));
        }
        fn cramp_set_levels(&mut self, _: i32, _: i32) {}
        fn cramp_ramp(&mut self) {}
        fn cramp_get_levels(&mut self) -> (i32, i32) {
            (3, 250)
        }
        fn info_set_bw(&mut self, _: i32, _: i32) {}
        fn info_slider_to_level(&mut self, n: i32) -> i32 {
            n
        }
        fn draw(&mut self, n: i32) {
            self.calls.push(format!("draw:{n}"));
        }
        fn auto_patch(&mut self, _: &mut [u8], _: &mut [i32], _: &mut [i32], _: i32, _: i32) {}
        fn auto_shrink(&mut self, _: &mut [u8], _: i32, _: i32) {}
        fn auto_expand(&mut self, _: &mut [u8], _: i32, _: i32) {}
        fn current_section(&mut self, _: i32, _: bool) -> Option<Vec<u8>> {
            Some(self.image.clone())
        }
        fn model_has_object(&mut self) -> bool {
            true
        }
        fn contours_from_image_points(
            &mut self,
            _: &[u8],
            _: &[u8],
            _: i32,
            _: i32,
            _: i32,
            _: u8,
            _: i32,
            _: f32,
            _: i32,
        ) -> Vec<AutoxContour> {
            vec![]
        }
        fn current_contour_surface(&mut self) -> i32 {
            0
        }
        fn prepare_contour_for_autox(&mut self) -> bool {
            true
        }
        fn copy_autox_contour(&mut self, _: &AutoxContour, _: i32) {}
        fn set_new_contour_time(&mut self) {}
        fn contour_strip(&mut self) {}
        fn contour_reduce(&mut self, _: f64) {}
        fn undo_finish_unit(&mut self) {}
        fn current_contour_center_of_mass(&mut self) -> Option<(f32, f32)> {
            None
        }
        fn iproc_busy(&mut self) -> bool {
            self.busy
        }
        fn print(&mut self, s: &str) {
            self.calls.push(s.into())
        }
        fn iproc_update(&mut self) {}
        fn iproc_call_when_free(&mut self) {}
        fn create_autox_window(&mut self) -> bool {
            true
        }
        fn raise_autox_window(&mut self) {}
        fn set_autox_window_states(&mut self, _: i32, _: i32, _: i32, _: i32, _: i32) {}
        fn show_autox_window(&mut self) {}
        fn close_autox_window(&mut self) {}
        fn free_full_section(&mut self) {}
        fn cramp_selected_index(&mut self) -> i32 {
            0
        }
    }
    fn view() -> AutoxView {
        AutoxView {
            xsize: 3,
            ysize: 3,
            zsize: 2,
            xysize: 9,
            xmouse: 1.,
            ymouse: 1.,
            rampsize: 256,
            ..Default::default()
        }
    }
    #[test]
    fn flood_matches_source_four_connected_region() {
        let mut v = view();
        let mut a = Autox::default();
        assert_eq!(allocate_arrays(&v, &mut a), 0);
        a.threshold = 10;
        let mut n = Native {
            image: vec![20, 20, 0, 20, 20, 0, 0, 0, 0],
            ..Default::default()
        };
        assert_eq!(
            autox_flood(&mut AutoxState::default(), &mut a, &v, &mut n),
            1
        );
        assert_eq!(a.data.iter().filter(|&&x| x & AUTOX_FLOOD != 0).count(), 4);
        autox_setlow(&mut a, &v, 1, 1, &mut n);
        assert_eq!(a.data[4] & AUTOX_BLACK, AUTOX_BLACK);
        autox_slider(&mut a, 1, 25, &mut v, &mut n);
        assert_eq!(a.shave, 0.25);
    }
    #[test]
    fn diagonal_mode_has_source_connectivity() {
        let v = view();
        let mut a = Autox::default();
        allocate_arrays(&v, &mut a);
        a.threshold = 10;
        a.diagonal = 1;
        let mut n = Native {
            image: vec![20, 0, 0, 0, 20, 0, 0, 0, 20],
            ..Default::default()
        };
        autox_flood(&mut AutoxState::default(), &mut a, &v, &mut n);
        assert_eq!(a.data.iter().filter(|&&x| x & AUTOX_FLOOD != 0).count(), 3);
    }
    #[test]
    fn next_keeps_busy_abort_and_z_direction() {
        let mut v = view();
        v.zmouse = 0.;
        let mut n = Native::default();
        autox_next_action(&mut v, &mut n);
        assert_eq!(v.zmouse, 1.);
        n.busy = true;
        autox_next_action(&mut v, &mut n);
        assert!(n.calls.iter().any(|x| x.contains("aborted")));
    }
}
