use clap::Parser;
use imod_model::{read_model, ImodModel};
use std::fs::File;
use std::io::{self, BufWriter, Write};

// Mesh index list sentinel values
const IMOD_MESH_ENDPOLY: i32 = -23;
const IMOD_MESH_BGNPOLYNORM: i32 = -21;
const IMOD_MESH_BGNPOLYNORM2: i32 = -24;
const IMOD_MESH_BGNPOLY: i32 = -20;
const IMOD_MESH_BGNBIGPOLY: i32 = -25;
const IMOD_MESH_END: i32 = -22;

const IMOD_OBJFLAG_SCAT: u32 = 1 << 9;
const IMOD_OBJFLAG_MESH: u32 = 1 << 10;

/// Convert an IMOD model file to the Pixar RenderMan RIB format.
///
/// The RenderMan(R) Interface Procedures and RIB Protocol are
/// Copyright 1988, 1989, Pixar. All rights reserved.
/// RenderMan(R) is a registered trademark of Pixar.
#[derive(Parser)]
#[command(name = "imod2rib", about = "Convert IMOD model to RenderMan RIB format")]
struct Args {
    /// Input IMOD model file
    input: String,

    /// Output RIB file
    output: String,
}

fn main() {
    let args = Args::parse();

    let model = read_model(&args.input).unwrap_or_else(|e| {
        eprintln!("Imod2RIB: Error reading model: {}", e);
        std::process::exit(3);
    });

    let fout = File::create(&args.output).unwrap_or_else(|e| {
        eprintln!("Couldn't open output file {}: {}", args.output, e);
        std::process::exit(10);
    });
    let mut w = BufWriter::new(fout);

    if let Err(e) = imod_to_rib(&model, &mut w) {
        eprintln!("Imod2RIB: Error writing: {}", e);
        std::process::exit(1);
    }
}

/// Write the model as RenderMan RIB format.
fn imod_to_rib(model: &ImodModel, w: &mut impl Write) -> io::Result<()> {
    let xs = model.scale.x;
    let ys = model.scale.y;
    let zs = model.scale.z;

    writeln!(w, "##RenderMan RIB")?;
    writeln!(w, "# Generated by imod2rib")?;
    writeln!(w, "FrameBegin 1")?;
    writeln!(w, "WorldBegin")?;

    for (ob, obj) in model.objects.iter().enumerate() {
        writeln!(w)?;
        writeln!(w, "# Object {}: {}", ob + 1, obj.name)?;
        writeln!(w, "AttributeBegin")?;
        writeln!(w, "  Color [{} {} {}]", obj.red, obj.green, obj.blue)?;
        writeln!(
            w,
            "  Surface \"plastic\" \"Kd\" {} \"Ks\" 0.3",
            0.8_f32
        )?;

        let use_mesh = (obj.flags & IMOD_OBJFLAG_MESH) != 0;

        if use_mesh {
            for mesh in &obj.meshes {
                let indices = &mesh.indices;
                let mut i = 0;
                while i < indices.len() {
                    let cmd = indices[i];
                    match cmd {
                        IMOD_MESH_BGNPOLYNORM | IMOD_MESH_BGNPOLYNORM2 => {
                            let (list_inc, vert_base, _norm_add) = mesh_poly_norm_factors(cmd);
                            i += 1;
                            while i < indices.len() && indices[i] != IMOD_MESH_ENDPOLY {
                                writeln!(w, "  Polygon \"P\" [")?;
                                for _ in 0..3 {
                                    if i + vert_base >= indices.len() {
                                        break;
                                    }
                                    let vi = indices[i + vert_base] as usize;
                                    if vi < mesh.vertices.len() {
                                        let v = &mesh.vertices[vi];
                                        write!(
                                            w,
                                            "    {} {} {}",
                                            v.x * xs,
                                            v.y * ys,
                                            v.z * zs
                                        )?;
                                    }
                                    i += list_inc;
                                }
                                writeln!(w, "\n  ]")?;
                            }
                        }
                        IMOD_MESH_BGNPOLY | IMOD_MESH_BGNBIGPOLY => {
                            i += 1;
                            while i < indices.len() && indices[i] != IMOD_MESH_ENDPOLY {
                                i += 1;
                            }
                        }
                        IMOD_MESH_END => break,
                        _ => {}
                    }
                    i += 1;
                }
            }
        } else if (obj.flags & IMOD_OBJFLAG_SCAT) != 0 {
            // Scattered points as spheres
            let r = obj.pdrawsize as f32 * 0.5;
            for cont in &obj.contours {
                for pt in &cont.points {
                    writeln!(w, "  TransformBegin")?;
                    writeln!(
                        w,
                        "    Translate {} {} {}",
                        pt.x * xs,
                        pt.y * ys,
                        pt.z * zs
                    )?;
                    writeln!(w, "    Sphere {} -{} {} 360", r, r, r)?;
                    writeln!(w, "  TransformEnd")?;
                }
            }
        } else {
            // Closed contours as polygons
            for cont in &obj.contours {
                if cont.points.len() < 3 {
                    continue;
                }
                writeln!(w, "  Polygon \"P\" [")?;
                for pt in &cont.points {
                    writeln!(
                        w,
                        "    {} {} {}",
                        (pt.x + model.offset.x) * xs,
                        (pt.y + model.offset.y) * ys,
                        (pt.z + model.offset.z) * zs
                    )?;
                }
                writeln!(w, "  ]")?;
            }
        }

        writeln!(w, "AttributeEnd")?;
    }

    writeln!(w, "WorldEnd")?;
    writeln!(w, "FrameEnd")?;
    Ok(())
}

fn mesh_poly_norm_factors(cmd: i32) -> (usize, usize, usize) {
    match cmd {
        IMOD_MESH_BGNPOLYNORM => (2, 0, 1),
        IMOD_MESH_BGNPOLYNORM2 => (1, 0, 0),
        _ => (0, 0, 0),
    }
}
