//! Owned generic translation of `IMOD/raptor/opencv/cxcopy.cpp`.
//!
//! The source dispatches macro-generated byte/pixel kernels through C function
//! tables.  The matrix representation already records element strides and
//! channels, so the same kernels are direct generic loops here.

use super::cxerror::CvStatus;
use super::cxminmaxloc::{CvMask, CvMatrix};

/// C `cvCopy`, including the source's masked row/stride behavior.
pub fn cv_copy<T: Copy>(
    source: &CvMatrix<T>,
    destination: &mut CvMatrix<T>,
    mask: Option<&CvMask>,
) -> Result<(), CvStatus> {
    if source.rows != destination.rows || source.columns != destination.columns {
        return Err(CvStatus::sts_unmatched_sizes);
    }
    if source.channels != destination.channels {
        return Err(CvStatus::sts_unmatched_formats);
    }
    if let Some(mask) = mask {
        if mask.row_stride < source.columns
            || mask.values.len() < (source.rows - 1) * mask.row_stride + source.columns
        {
            return Err(CvStatus::sts_bad_mask);
        }
    }
    for row in 0..source.rows {
        for column in 0..source.columns {
            if mask.is_some_and(|mask| mask.values[row * mask.row_stride + column] == 0) {
                continue;
            }
            let source_start = row * source.row_stride + column * source.channels;
            let destination_start = row * destination.row_stride + column * destination.channels;
            destination.values[destination_start..destination_start + source.channels]
                .copy_from_slice(&source.values[source_start..source_start + source.channels]);
        }
    }
    Ok(())
}

/// C `cvCopy`'s `cvSplit`/`cvMerge` COI paths.
///
/// `source_coi` extracts one one-based source channel into a single-channel
/// destination; `destination_coi` inserts a single source channel.  C rejects
/// a mask on either COI path and does not permit both directions at once.
pub fn cv_copy_coi<T: Copy>(
    source: &CvMatrix<T>,
    destination: &mut CvMatrix<T>,
    source_coi: Option<usize>,
    destination_coi: Option<usize>,
    mask: Option<&CvMask>,
) -> Result<(), CvStatus> {
    if mask.is_some() && (source_coi.is_some() || destination_coi.is_some()) {
        return Err(CvStatus::sts_bad_arg);
    }
    if source_coi.is_some() && destination_coi.is_some() {
        return Err(CvStatus::sts_bad_arg);
    }
    if source_coi.is_none() && destination_coi.is_none() {
        return cv_copy(source, destination, mask);
    }
    if source.rows != destination.rows || source.columns != destination.columns {
        return Err(CvStatus::sts_unmatched_sizes);
    }
    let (input_channels, output_channels, selected_channel, extracting) =
        match (source_coi, destination_coi) {
            (Some(channel), None) => (source.channels, destination.channels, channel, true),
            (None, Some(channel)) => (destination.channels, source.channels, channel, false),
            (None, None) => unreachable!(),
            (Some(_), Some(_)) => unreachable!(),
        };
    if output_channels != 1 || selected_channel == 0 || selected_channel > input_channels {
        return Err(CvStatus::bad_coi);
    }
    let selected_channel = selected_channel - 1;
    for row in 0..source.rows {
        for column in 0..source.columns {
            if extracting {
                destination.values[row * destination.row_stride + column] = source.values
                    [row * source.row_stride + column * source.channels + selected_channel];
            } else {
                destination.values[row * destination.row_stride
                    + column * destination.channels
                    + selected_channel] = source.values[row * source.row_stride + column];
            }
        }
    }
    Ok(())
}

/// C `cvSet`; scalar entries repeat over channels as `cvScalarToRawData` does.
pub fn cv_set<T: Copy>(
    matrix: &mut CvMatrix<T>,
    scalar: &[T],
    mask: Option<&CvMask>,
) -> Result<(), CvStatus> {
    if scalar.is_empty() {
        return Err(CvStatus::sts_bad_arg);
    }
    if let Some(mask) = mask {
        if mask.row_stride < matrix.columns
            || mask.values.len() < (matrix.rows - 1) * mask.row_stride + matrix.columns
        {
            return Err(CvStatus::sts_bad_mask);
        }
    }
    for row in 0..matrix.rows {
        for column in 0..matrix.columns {
            if mask.is_some_and(|mask| mask.values[row * mask.row_stride + column] == 0) {
                continue;
            }
            let start = row * matrix.row_stride + column * matrix.channels;
            for channel in 0..matrix.channels {
                matrix.values[start + channel] = scalar[channel % scalar.len()];
            }
        }
    }
    Ok(())
}

/// C `icvSetZero_8u_C1R` and public `cvSetZero`/`cvZero`.
pub fn cv_set_zero<T: Default>(matrix: &mut CvMatrix<T>) {
    for row in 0..matrix.rows {
        for column in 0..matrix.columns {
            let start = row * matrix.row_stride + column * matrix.channels;
            for value in &mut matrix.values[start..start + matrix.channels] {
                *value = T::default();
            }
        }
    }
}

/// C `cvFlip` into a distinct destination. Modes are the C values: zero is
/// vertical, positive is horizontal, and negative flips both axes.
pub fn cv_flip<T: Copy>(
    source: &CvMatrix<T>,
    destination: &mut CvMatrix<T>,
    flip_mode: i32,
) -> Result<(), CvStatus> {
    if source.rows != destination.rows || source.columns != destination.columns {
        return Err(CvStatus::sts_unmatched_sizes);
    }
    if source.channels != destination.channels {
        return Err(CvStatus::sts_unmatched_formats);
    }
    for row in 0..source.rows {
        for column in 0..source.columns {
            let source_row = if flip_mode <= 0 {
                source.rows - row - 1
            } else {
                row
            };
            let source_column = if flip_mode != 0 {
                source.columns - column - 1
            } else {
                column
            };
            let source_start = source_row * source.row_stride + source_column * source.channels;
            let destination_start = row * destination.row_stride + column * destination.channels;
            destination.values[destination_start..destination_start + source.channels]
                .copy_from_slice(&source.values[source_start..source_start + source.channels]);
        }
    }
    Ok(())
}

/// C `cvFlip` when `src == dst`.
pub fn cv_flip_in_place<T: Copy>(matrix: &mut CvMatrix<T>, flip_mode: i32) {
    for row in 0..matrix.rows {
        for column in 0..matrix.columns {
            let paired_row = if flip_mode <= 0 {
                matrix.rows - row - 1
            } else {
                row
            };
            let paired_column = if flip_mode != 0 {
                matrix.columns - column - 1
            } else {
                column
            };
            if (row, column) > (paired_row, paired_column) {
                continue;
            }
            let start = row * matrix.row_stride + column * matrix.channels;
            let paired_start = paired_row * matrix.row_stride + paired_column * matrix.channels;
            for channel in 0..matrix.channels {
                matrix.values.swap(start + channel, paired_start + channel);
            }
        }
    }
}

/// C `cvRepeat`.
pub fn cv_repeat<T: Copy>(
    source: &CvMatrix<T>,
    destination: &mut CvMatrix<T>,
) -> Result<(), CvStatus> {
    if source.channels != destination.channels {
        return Err(CvStatus::sts_unmatched_formats);
    }
    for row in 0..destination.rows {
        for column in 0..destination.columns {
            let source_row = row % source.rows;
            let source_column = column % source.columns;
            let source_start = source_row * source.row_stride + source_column * source.channels;
            let destination_start = row * destination.row_stride + column * destination.channels;
            destination.values[destination_start..destination_start + source.channels]
                .copy_from_slice(&source.values[source_start..source_start + source.channels]);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{cv_copy, cv_copy_coi, cv_flip, cv_flip_in_place, cv_repeat, cv_set, cv_set_zero};
    use crate::imod::raptor::opencv::cxerror::CvStatus;
    use crate::imod::raptor::opencv::cxminmaxloc::{CvMask, CvMatrix};

    #[test]
    fn copy_and_set_respect_mask_channel_and_stride() {
        let source = CvMatrix::new(
            2,
            2,
            3,
            7,
            vec![1_u8, 2, 3, 4, 5, 6, 99, 7, 8, 9, 10, 11, 12, 99],
        )
        .unwrap();
        let mut destination = CvMatrix::new(2, 2, 3, 7, vec![0_u8; 14]).unwrap();
        let mask = CvMask::new(2, 2, 2, vec![1, 0, 0, 1]).unwrap();
        cv_copy(&source, &mut destination, Some(&mask)).unwrap();
        assert_eq!(&destination.values[..6], &[1, 2, 3, 0, 0, 0]);
        assert_eq!(&destination.values[7..13], &[0, 0, 0, 10, 11, 12]);
        cv_set(&mut destination, &[8, 7, 6], Some(&mask)).unwrap();
        assert_eq!(&destination.values[..6], &[8, 7, 6, 0, 0, 0]);
    }

    #[test]
    fn coi_extracts_and_inserts_without_mask() {
        let source = CvMatrix::new(1, 2, 3, 6, vec![1_i16, 2, 3, 4, 5, 6]).unwrap();
        let mut plane = CvMatrix::new(1, 2, 1, 2, vec![0_i16; 2]).unwrap();
        cv_copy_coi(&source, &mut plane, Some(2), None, None).unwrap();
        assert_eq!(plane.values, [2, 5]);
        cv_copy_coi(
            &plane,
            &mut source.clone(),
            None,
            Some(3),
            Some(&CvMask::new(1, 2, 2, vec![1, 1]).unwrap()),
        )
        .unwrap_err();
        let mut merged = CvMatrix::new(1, 2, 3, 6, vec![0_i16; 6]).unwrap();
        cv_copy_coi(&plane, &mut merged, None, Some(3), None).unwrap();
        assert_eq!(merged.values, [0, 0, 2, 0, 0, 5]);
    }

    #[test]
    fn flip_matches_source_modes_and_in_place_path() {
        let source = CvMatrix::new(2, 3, 1, 3, vec![1_u8, 2, 3, 4, 5, 6]).unwrap();
        let mut destination = CvMatrix::new(2, 3, 1, 3, vec![0_u8; 6]).unwrap();
        cv_flip(&source, &mut destination, -1).unwrap();
        assert_eq!(destination.values, [6, 5, 4, 3, 2, 1]);
        cv_flip_in_place(&mut destination, -1);
        assert_eq!(destination.values, source.values);
    }

    #[test]
    fn repeat_zero_and_format_failure_follow_public_operations() {
        let source = CvMatrix::new(1, 2, 1, 2, vec![4_i32, 9]).unwrap();
        let mut destination = CvMatrix::new(3, 5, 1, 5, vec![1_i32; 15]).unwrap();
        cv_repeat(&source, &mut destination).unwrap();
        assert_eq!(&destination.values[..5], &[4, 9, 4, 9, 4]);
        cv_set_zero(&mut destination);
        assert!(destination.values.iter().all(|value| *value == 0));
        let mut mismatched = CvMatrix::new(1, 2, 2, 4, vec![0_i32; 4]).unwrap();
        assert_eq!(
            cv_copy(&source, &mut mismatched, None),
            Err(CvStatus::sts_unmatched_formats)
        );
    }
}
