//! Lookup-table transforms from `IMOD/raptor/opencv/cxlut.cpp`.
//!
//! The C entry points operate on byte pointers and byte strides.  This
//! translation retains byte strides at the corresponding low-level entry
//! points, but uses slices and owned matrices rather than untyped pointers.

/// `CvSize` for the LUT kernels.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct LutSize {
    pub width: usize,
    pub height: usize,
}

/// Safe replacement for the `CvStatus` failures reachable from this unit.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LutError {
    BadArgument,
    UnmatchedSizes,
    UnmatchedFormats,
    UnsupportedFormat,
}

/// An owned, interleaved matrix accepted by [`cv_lut`].
#[derive(Clone, Debug, PartialEq)]
pub struct LutMatrix<T> {
    pub rows: usize,
    pub columns: usize,
    pub channels: usize,
    pub data: Vec<T>,
}

/// The two source depths accepted by the original `cvLUT` API.
#[derive(Clone, Debug, PartialEq)]
pub enum LutSource {
    Unsigned(LutMatrix<u8>),
    Signed(LutMatrix<i8>),
}

macro_rules! define_lut_c1 {
    ($name:ident, $type:ty) => {
        /// C1 LUT kernel generated by `ICV_DEF_LUT_FUNC_8U_CN`.
        pub fn $name(
            src: &[u8],
            src_step: usize,
            dst: &mut [$type],
            dst_step: usize,
            size: LutSize,
            lut: &[$type],
        ) -> Result<(), LutError> {
            if lut.len() < 256
                || src_step < size.width
                || dst_step % core::mem::size_of::<$type>() != 0
            {
                return Err(LutError::BadArgument);
            }
            let dst_step = dst_step / core::mem::size_of::<$type>();
            if src.len() < size.height.saturating_sub(1).saturating_mul(src_step) + size.width
                || dst.len() < size.height.saturating_sub(1).saturating_mul(dst_step) + size.width
            {
                return Err(LutError::BadArgument);
            }
            for row in 0..size.height {
                let src_row = row * src_step;
                let dst_row = row * dst_step;
                let mut column = 0;
                while column + 4 <= size.width {
                    dst[dst_row + column] = lut[src[src_row + column] as usize];
                    dst[dst_row + column + 1] = lut[src[src_row + column + 1] as usize];
                    dst[dst_row + column + 2] = lut[src[src_row + column + 2] as usize];
                    dst[dst_row + column + 3] = lut[src[src_row + column + 3] as usize];
                    column += 4;
                }
                while column < size.width {
                    dst[dst_row + column] = lut[src[src_row + column] as usize];
                    column += 1;
                }
            }
            Ok(())
        }
    };
}

macro_rules! define_lut_cn_u8 {
    ($name:ident, $channels:expr) => {
        /// Interleaved `u8` LUT kernel generated by `ICV_DEF_LUT_FUNC_8U_CN`.
        pub fn $name(
            src: &[u8],
            src_step: usize,
            dst: &mut [u8],
            dst_step: usize,
            size: LutSize,
            lut: &[u8],
        ) -> Result<(), LutError> {
            let width = size
                .width
                .checked_mul($channels)
                .ok_or(LutError::BadArgument)?;
            if lut.len() < 256 * $channels
                || src_step < width
                || dst_step < width
                || src.len() < size.height.saturating_sub(1).saturating_mul(src_step) + width
                || dst.len() < size.height.saturating_sub(1).saturating_mul(dst_step) + width
            {
                return Err(LutError::BadArgument);
            }
            for row in 0..size.height {
                let src_row = row * src_step;
                let dst_row = row * dst_step;
                for column in (0..width).step_by($channels) {
                    for channel in 0..$channels {
                        dst[dst_row + column + channel] =
                            lut[src[src_row + column + channel] as usize * $channels + channel];
                    }
                }
            }
            Ok(())
        }
    };
}

macro_rules! define_lut_cn {
    ($name:ident, $type:ty) => {
        /// General-channel LUT kernel generated by `ICV_DEF_LUT_FUNC_8U`.
        pub fn $name(
            src: &[u8],
            src_step: usize,
            dst: &mut [$type],
            dst_step: usize,
            size: LutSize,
            lut: &[$type],
            channels: usize,
        ) -> Result<(), LutError> {
            let width = size
                .width
                .checked_mul(channels)
                .ok_or(LutError::BadArgument)?;
            if channels == 0
                || lut.len() < 256 * channels
                || src_step < width
                || dst_step % core::mem::size_of::<$type>() != 0
            {
                return Err(LutError::BadArgument);
            }
            let dst_step = dst_step / core::mem::size_of::<$type>();
            if src.len() < size.height.saturating_sub(1).saturating_mul(src_step) + width
                || dst.len() < size.height.saturating_sub(1).saturating_mul(dst_step) + width
            {
                return Err(LutError::BadArgument);
            }
            for row in 0..size.height {
                let src_row = row * src_step;
                let dst_row = row * dst_step;
                for column in (0..width).step_by(channels) {
                    for channel in 0..channels {
                        dst[dst_row + column + channel] =
                            lut[src[src_row + column + channel] as usize * channels + channel];
                    }
                }
            }
            Ok(())
        }
    };
}

define_lut_c1!(icv_lut_transform8u_8u_c1r, u8);
define_lut_c1!(icv_lut_transform8u_16u_c1r, u16);
define_lut_c1!(icv_lut_transform8u_32s_c1r, i32);
define_lut_c1!(icv_lut_transform8u_64f_c1r, f64);
define_lut_cn_u8!(icv_lut_transform8u_8u_c2r, 2);
define_lut_cn_u8!(icv_lut_transform8u_8u_c3r, 3);
define_lut_cn_u8!(icv_lut_transform8u_8u_c4r, 4);
define_lut_cn!(icv_lut_transform8u_8u_cnr, u8);
define_lut_cn!(icv_lut_transform8u_16u_cnr, u16);
define_lut_cn!(icv_lut_transform8u_32s_cnr, i32);
define_lut_cn!(icv_lut_transform8u_64f_cnr, f64);

/// Header inline alias for the `i8` destination C1 kernel.
pub fn icv_lut_transform8u_8s_c1r(
    src: &[u8],
    src_step: usize,
    dst: &mut [i8],
    dst_step: usize,
    size: LutSize,
    lut: &[i8],
) -> Result<(), LutError> {
    if lut.len() < 256
        || src_step < size.width
        || dst_step < size.width
        || src.len() < size.height.saturating_sub(1).saturating_mul(src_step) + size.width
        || dst.len() < size.height.saturating_sub(1).saturating_mul(dst_step) + size.width
    {
        return Err(LutError::BadArgument);
    }
    for row in 0..size.height {
        for column in 0..size.width {
            dst[row * dst_step + column] = lut[src[row * src_step + column] as usize];
        }
    }
    Ok(())
}

/// Header inline alias for the `i16` destination C1 kernel.
pub fn icv_lut_transform8u_16s_c1r(
    src: &[u8],
    src_step: usize,
    dst: &mut [i16],
    dst_step: usize,
    size: LutSize,
    lut: &[i16],
) -> Result<(), LutError> {
    if lut.len() < 256
        || src_step < size.width
        || dst_step < size.width
        || src.len() < size.height.saturating_sub(1).saturating_mul(src_step) + size.width
        || dst.len() < size.height.saturating_sub(1).saturating_mul(dst_step) + size.width
    {
        return Err(LutError::BadArgument);
    }
    for row in 0..size.height {
        for column in 0..size.width {
            dst[row * dst_step + column] = lut[src[row * src_step + column] as usize];
        }
    }
    Ok(())
}

/// Header inline alias for the `f32` destination C1 kernel.
pub fn icv_lut_transform8u_32f_c1r(
    src: &[u8],
    src_step: usize,
    dst: &mut [f32],
    dst_step: usize,
    size: LutSize,
    lut: &[f32],
) -> Result<(), LutError> {
    if lut.len() < 256
        || src_step < size.width
        || dst_step < size.width
        || src.len() < size.height.saturating_sub(1).saturating_mul(src_step) + size.width
        || dst.len() < size.height.saturating_sub(1).saturating_mul(dst_step) + size.width
    {
        return Err(LutError::BadArgument);
    }
    for row in 0..size.height {
        for column in 0..size.width {
            dst[row * dst_step + column] = lut[src[row * src_step + column] as usize];
        }
    }
    Ok(())
}

/// Owned safe translation of `cvLUT`.
pub fn cv_lut<T: Copy>(
    source: &LutSource,
    destination: &mut LutMatrix<T>,
    table: &LutMatrix<T>,
) -> Result<(), LutError> {
    let (rows, columns, channels, source_data) = match source {
        LutSource::Unsigned(matrix)
            if matrix
                .rows
                .checked_mul(matrix.columns)
                .and_then(|count| count.checked_mul(matrix.channels))
                == Some(matrix.data.len()) =>
        {
            (
                matrix.rows,
                matrix.columns,
                matrix.channels,
                matrix
                    .data
                    .iter()
                    .map(|&value| value as usize)
                    .collect::<Vec<_>>(),
            )
        }
        LutSource::Signed(matrix)
            if matrix
                .rows
                .checked_mul(matrix.columns)
                .and_then(|count| count.checked_mul(matrix.channels))
                == Some(matrix.data.len()) =>
        {
            (
                matrix.rows,
                matrix.columns,
                matrix.channels,
                matrix
                    .data
                    .iter()
                    .map(|&value| (value as i16 + 128) as usize)
                    .collect::<Vec<_>>(),
            )
        }
        _ => return Err(LutError::BadArgument),
    };
    if destination
        .rows
        .checked_mul(destination.columns)
        .and_then(|count| count.checked_mul(destination.channels))
        != Some(destination.data.len())
        || table
            .rows
            .checked_mul(table.columns)
            .and_then(|count| count.checked_mul(table.channels))
            != Some(table.data.len())
        || destination.rows != rows
        || destination.columns != columns
    {
        return Err(LutError::UnmatchedSizes);
    }
    if destination.channels != channels {
        return Err(LutError::UnmatchedFormats);
    }
    if table
        .rows
        .checked_mul(table.columns)
        .and_then(|count| count.checked_mul(table.channels))
        != Some(256 * table.channels)
        || (table.channels != 1 && table.channels != channels)
    {
        return Err(LutError::BadArgument);
    }
    for (index, &value) in source_data.iter().enumerate() {
        let channel = index % channels;
        destination.data[index] =
            table.data[value * table.channels + if table.channels == 1 { 0 } else { channel }];
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c1_kernels_preserve_rows_and_byte_strides() {
        let source = [0, 2, 3, 0, 1, 4, 5, 0];
        let mut destination = [99_u16; 8];
        let table: Vec<u16> = (0..256).map(|value| value * 11).collect();
        icv_lut_transform8u_16u_c1r(
            &source,
            4,
            &mut destination,
            8,
            LutSize {
                width: 3,
                height: 2,
            },
            &table,
        )
        .unwrap();
        assert_eq!(destination, [0, 22, 33, 99, 11, 44, 55, 99]);
    }

    #[test]
    fn interleaved_kernels_select_each_channel_table() {
        let source = [1, 2, 3, 4, 5, 6];
        let mut destination = [0; 6];
        let mut table = vec![0; 256 * 3];
        for value in 0..256 {
            for channel in 0..3 {
                table[value * 3 + channel] = (value + channel * 40) as u8;
            }
        }
        icv_lut_transform8u_8u_c3r(
            &source,
            6,
            &mut destination,
            6,
            LutSize {
                width: 2,
                height: 1,
            },
            &table,
        )
        .unwrap();
        assert_eq!(destination, [1, 42, 83, 4, 45, 86]);
    }

    #[test]
    fn cv_lut_handles_signed_input_with_the_source_shuffle() {
        let source = LutSource::Signed(LutMatrix {
            rows: 1,
            columns: 3,
            channels: 1,
            data: vec![-128, 0, 127],
        });
        let table = LutMatrix {
            rows: 1,
            columns: 256,
            channels: 1,
            data: (0..256).map(|value| value as i32).collect(),
        };
        let mut destination = LutMatrix {
            rows: 1,
            columns: 3,
            channels: 1,
            data: vec![0_i32; 3],
        };
        cv_lut(&source, &mut destination, &table).unwrap();
        assert_eq!(destination.data, [0, 128, 255]);
    }
}
