//! Owned generic translation of `IMOD/raptor/opencv/cxminmaxloc.cpp`.
//!
//! The source generates fourteen raw-pointer kernels from macros: each of six
//! scalar depths has one- and multi-channel variants, with and without a
//! mask. `CvMatrix` and `CvMinMaxElement` express those generated kernels as
//! one bounds-checked Rust generic implementation.

use super::cvutils::CvPoint;
use super::cxerror::CvStatus;

/// Owned dimensions and strided interleaved data accepted by C `cvMinMaxLoc`.
#[derive(Clone, Debug, PartialEq)]
pub struct CvMatrix<T> {
    pub rows: usize,
    pub columns: usize,
    pub channels: usize,
    pub row_stride: usize,
    pub values: Vec<T>,
}

impl<T> CvMatrix<T> {
    /// Creates a matrix whose row stride is measured in scalar elements.
    pub fn new(
        rows: usize,
        columns: usize,
        channels: usize,
        row_stride: usize,
        values: Vec<T>,
    ) -> Result<Self, CvStatus> {
        if rows == 0 || columns == 0 || channels == 0 || row_stride < columns * channels {
            return Err(CvStatus::sts_bad_size);
        }
        let required = (rows - 1)
            .checked_mul(row_stride)
            .and_then(|start| start.checked_add(columns * channels))
            .ok_or(CvStatus::sts_bad_size)?;
        if values.len() < required {
            return Err(CvStatus::sts_bad_size);
        }
        Ok(Self {
            rows,
            columns,
            channels,
            row_stride,
            values,
        })
    }
}

/// C's 8-bit single-channel mask, with its independent element stride.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CvMask {
    pub row_stride: usize,
    pub values: Vec<u8>,
}

impl CvMask {
    pub fn new(
        rows: usize,
        columns: usize,
        row_stride: usize,
        values: Vec<u8>,
    ) -> Result<Self, CvStatus> {
        if rows == 0 || columns == 0 || row_stride < columns {
            return Err(CvStatus::sts_bad_mask);
        }
        let required = (rows - 1)
            .checked_mul(row_stride)
            .and_then(|start| start.checked_add(columns))
            .ok_or(CvStatus::sts_bad_mask)?;
        if values.len() < required {
            return Err(CvStatus::sts_bad_mask);
        }
        Ok(Self { row_stride, values })
    }
}

/// The value/location result formerly written through four C output pointers.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CvMinMaxLoc {
    pub min_value: f64,
    pub max_value: f64,
    pub min_location: CvPoint,
    pub max_location: CvPoint,
}

/// Scalar depths generated by the source's `ICV_DEF_MINMAXLOC_*` macros.
pub trait CvMinMaxElement: Copy {
    fn as_f64(self) -> f64;
    fn less_than(self, other: Self) -> bool;
    fn greater_than(self, other: Self) -> bool;
}

macro_rules! impl_min_max_element {
    ($($type:ty),+ $(,)?) => {
        $(
            impl CvMinMaxElement for $type {
                fn as_f64(self) -> f64 { self as f64 }
                fn less_than(self, other: Self) -> bool { self < other }
                fn greater_than(self, other: Self) -> bool { self > other }
            }
        )+
    };
}

impl_min_max_element!(u8, u16, i16, i32);

impl CvMinMaxElement for f32 {
    fn as_f64(self) -> f64 {
        self as f64
    }
    fn less_than(self, other: Self) -> bool {
        self.total_cmp(&other).is_lt()
    }
    fn greater_than(self, other: Self) -> bool {
        self.total_cmp(&other).is_gt()
    }
}

impl CvMinMaxElement for f64 {
    fn as_f64(self) -> f64 {
        self
    }
    fn less_than(self, other: Self) -> bool {
        self.total_cmp(&other).is_lt()
    }
    fn greater_than(self, other: Self) -> bool {
        self.total_cmp(&other).is_gt()
    }
}

/// C `cvMinMaxLoc` and all macro-generated `icvMinMaxIndx_*` kernels.
///
/// `coi` is C's one-based channel of interest. It is required for a
/// multi-channel matrix, matching the source's rejection of `cn > 1 && coi ==
/// 0`. The first extremum in row-major order wins ties, as in the C loops.
pub fn cv_min_max_loc<T: CvMinMaxElement>(
    matrix: &CvMatrix<T>,
    coi: Option<usize>,
    mask: Option<&CvMask>,
) -> Result<CvMinMaxLoc, CvStatus> {
    let channel = match (matrix.channels, coi) {
        (1, None) | (1, Some(1)) => 0,
        (1, Some(_)) | (_, None) => return Err(CvStatus::sts_bad_arg),
        (_, Some(channel)) if channel == 0 || channel > matrix.channels => {
            return Err(CvStatus::sts_bad_arg);
        }
        (_, Some(channel)) => channel - 1,
    };
    if let Some(mask) = mask {
        if mask.row_stride < matrix.columns {
            return Err(CvStatus::sts_bad_mask);
        }
        let required = (matrix.rows - 1)
            .checked_mul(mask.row_stride)
            .and_then(|start| start.checked_add(matrix.columns))
            .ok_or(CvStatus::sts_bad_mask)?;
        if mask.values.len() < required {
            return Err(CvStatus::sts_bad_mask);
        }
    }

    let mut extrema: Option<(T, T, CvPoint, CvPoint)> = None;
    for row in 0..matrix.rows {
        for column in 0..matrix.columns {
            if mask.is_some_and(|mask| mask.values[row * mask.row_stride + column] == 0) {
                continue;
            }
            let value = matrix.values[row * matrix.row_stride + column * matrix.channels + channel];
            let location = CvPoint {
                x: i32::try_from(column).map_err(|_| CvStatus::sts_bad_size)?,
                y: i32::try_from(row).map_err(|_| CvStatus::sts_bad_size)?,
            };
            match &mut extrema {
                None => extrema = Some((value, value, location, location)),
                Some((min_value, max_value, min_location, max_location)) => {
                    if value.less_than(*min_value) {
                        *min_value = value;
                        *min_location = location;
                    } else if value.greater_than(*max_value) {
                        *max_value = value;
                        *max_location = location;
                    }
                }
            }
        }
    }

    Ok(match extrema {
        Some((min_value, max_value, min_location, max_location)) => CvMinMaxLoc {
            min_value: min_value.as_f64(),
            max_value: max_value.as_f64(),
            min_location,
            max_location,
        },
        None => CvMinMaxLoc {
            min_value: 0.0,
            max_value: 0.0,
            min_location: CvPoint { x: -1, y: -1 },
            max_location: CvPoint { x: -1, y: -1 },
        },
    })
}

#[cfg(test)]
mod tests {
    use super::{CvMask, CvMatrix, cv_min_max_loc};
    use crate::imod::raptor::opencv::cvutils::CvPoint;
    use crate::imod::raptor::opencv::cxerror::CvStatus;

    #[test]
    fn finds_first_tied_extrema_in_strided_single_channel_matrix() {
        let matrix = CvMatrix::new(2, 3, 1, 4, vec![3_i16, 1, 5, 99, 1, 8, 5, 99]).unwrap();
        assert_eq!(
            cv_min_max_loc(&matrix, None, None).unwrap(),
            super::CvMinMaxLoc {
                min_value: 1.0,
                max_value: 8.0,
                min_location: CvPoint { x: 1, y: 0 },
                max_location: CvPoint { x: 1, y: 1 },
            }
        );
    }

    #[test]
    fn coi_selects_one_based_channel_and_mask_preserves_2d_locations() {
        let matrix =
            CvMatrix::new(2, 2, 3, 6, vec![10_u8, 4, 9, 8, 7, 6, 5, 3, 2, 1, 12, 11]).unwrap();
        let mask = CvMask::new(2, 2, 2, vec![0, 1, 1, 1]).unwrap();
        assert_eq!(
            cv_min_max_loc(&matrix, Some(2), Some(&mask)).unwrap(),
            super::CvMinMaxLoc {
                min_value: 3.0,
                max_value: 12.0,
                min_location: CvPoint { x: 0, y: 1 },
                max_location: CvPoint { x: 1, y: 1 },
            }
        );
    }

    #[test]
    fn empty_mask_matches_source_zero_values_and_negative_locations() {
        let matrix = CvMatrix::new(1, 2, 1, 2, vec![7.0_f32, 2.0]).unwrap();
        let mask = CvMask::new(1, 2, 2, vec![0, 0]).unwrap();
        let result = cv_min_max_loc(&matrix, None, Some(&mask)).unwrap();
        assert_eq!(result.min_value, 0.0);
        assert_eq!(result.min_location, CvPoint { x: -1, y: -1 });
        assert_eq!(result.max_location, CvPoint { x: -1, y: -1 });
    }

    #[test]
    fn rejects_source_invalid_coi_and_mask_shapes() {
        let matrix = CvMatrix::new(1, 2, 2, 4, vec![1_u8, 2, 3, 4]).unwrap();
        assert_eq!(
            cv_min_max_loc(&matrix, None, None),
            Err(CvStatus::sts_bad_arg)
        );
        assert_eq!(
            cv_min_max_loc(&matrix, Some(3), None),
            Err(CvStatus::sts_bad_arg)
        );
        assert!(CvMask::new(1, 2, 1, vec![1, 1]).is_err());
    }
}
