use clap::Parser;
use imod_model::{read_model, ImodModel, ImodObject, ImodMesh, ImodContour};
use std::fs::File;
use std::io::{self, BufWriter, Write};

// IMOD object flag bits
const IMOD_OBJFLAG_OFF: u32 = 1 << 3;
const IMOD_OBJFLAG_SCAT: u32 = 1 << 9;
const IMOD_OBJFLAG_MESH: u32 = 1 << 10;
const IMOD_OBJFLAG_FILL: u32 = 1 << 13;
// const IMOD_OBJFLAG_FCOLOR: u32 = 1 << 14; // reserved for future use

// Mesh index list sentinel values
const IMOD_MESH_ENDPOLY: i32 = -23;
const IMOD_MESH_BGNPOLYNORM: i32 = -21;
const IMOD_MESH_BGNPOLYNORM2: i32 = -24;
const IMOD_MESH_END: i32 = -22;
#[allow(dead_code)]
const IMOD_MESH_BGNPOLY: i32 = -20;
#[allow(dead_code)]
const IMOD_MESH_BGNBIGPOLY: i32 = -25;

// Contour flag
const ICONT_OPEN: u32 = 1 << 3;

/// Convert an IMOD model to VRML 2.0 (Virtual Reality Modeling Language) format.
#[derive(Parser)]
#[command(name = "imod2vrml2", about = "Convert IMOD model to VRML2")]
struct Args {
    /// Output low-resolution meshes (if any exist)
    #[arg(short = 'l')]
    low_res: bool,

    /// Output all objects (by default those switched off are omitted)
    #[arg(short = 'a')]
    all_objects: bool,

    /// Rotate model so Z axis becomes up in Y
    #[arg(short = 'r')]
    rotate: bool,

    /// Don't assign names to child geometries
    #[arg(short = 'g')]
    no_geom_names: bool,

    /// Output normals
    #[arg(short = 'n')]
    normals: bool,

    /// Show all contour lines
    #[arg(short = 'c')]
    contours: bool,

    /// Input IMOD model file
    input: String,

    /// Output VRML2 file
    output: String,
}

struct Stats {
    num_objs: usize,
    num_vertices: usize,
    num_faces: usize,
    num_spheres: usize,
}

fn main() {
    let args = Args::parse();

    let model = read_model(&args.input).unwrap_or_else(|e| {
        eprintln!("Error reading model {}: {}", args.input, e);
        std::process::exit(3);
    });

    let fout = File::create(&args.output).unwrap_or_else(|e| {
        eprintln!("Couldn't open output file {}: {}", args.output, e);
        std::process::exit(10);
    });
    let mut w = BufWriter::new(fout);
    let mut stats = Stats {
        num_objs: 0,
        num_vertices: 0,
        num_faces: 0,
        num_spheres: 0,
    };

    imod_to_vrml2(&model, &mut w, &args, &mut stats).unwrap_or_else(|e| {
        eprintln!("Error writing VRML2: {}", e);
        std::process::exit(1);
    });

    println!("Finished writing '{}'", args.output);
    println!("  # objects on: {}", stats.num_objs);
    println!("  # spheres:    {}", stats.num_spheres);
    println!("  # vertices:   {}", stats.num_vertices);
    println!("  # faces:      {}", stats.num_faces);
}

fn vrml_safe_name(obj: &ImodObject, ob: usize) -> String {
    let mut name = format!("obj{}_", ob + 1);
    for c in obj.name.chars() {
        match c {
            ' ' | '\t' | '\n' => name.push('_'),
            '(' | '[' | '{' => name.push('<'),
            ')' | ']' | '}' => name.push('>'),
            '\'' | '"' => name.push('`'),
            '#' | '.' | ',' | '\\' | ':' | '+' | '&' | ';' | '|' => name.push('_'),
            _ => name.push(c),
        }
    }
    name
}

fn is_scat(flags: u32) -> bool {
    flags & IMOD_OBJFLAG_SCAT != 0
}

fn is_off(flags: u32) -> bool {
    flags & IMOD_OBJFLAG_OFF != 0
}

fn is_fill(flags: u32) -> bool {
    flags & IMOD_OBJFLAG_FILL != 0
}

fn is_mesh_flag(flags: u32) -> bool {
    flags & IMOD_OBJFLAG_MESH != 0
}

fn imod_to_vrml2(
    model: &ImodModel,
    w: &mut impl Write,
    args: &Args,
    stats: &mut Stats,
) -> io::Result<()> {
    writeln!(w, "#VRML V2.0 utf8")?;
    writeln!(w, "#Generated by IMOD\n")?;
    writeln!(w, "DEF imod_model Transform {{")?;
    if args.rotate {
        writeln!(w, "  rotation -1 0 0 1.570796   # rotate by -90 degrees in Z ")?;
    }
    writeln!(w, "  children [")?;

    for (ob, obj) in model.objects.iter().enumerate() {
        print_object(model, ob, obj, w, args, stats)?;
    }

    writeln!(w)?;
    writeln!(w, "  ]")?;
    writeln!(w, "}}")?;
    Ok(())
}

fn print_material(
    obj: &ImodObject,
    ob: usize,
    w: &mut impl Write,
) -> io::Result<()> {
    let ambient = 0.5_f32; // default
    let diffuse = 0.8_f32;
    let specular = 0.3_f32;
    let shininess = 0.25_f32.max(0.01);
    let (r, g, b) = (obj.red, obj.green, obj.blue);
    let safe_name = vrml_safe_name(obj, ob);

    writeln!(w)?;
    writeln!(w, "#MATERIAL FOR OBJECT {}:", ob + 1)?;
    writeln!(w, "Shape {{")?;
    write!(w, "  appearance DEF MAT_{} Appearance {{\n", safe_name)?;
    writeln!(w, "    material Material {{")?;
    writeln!(w, "      ambientIntensity {} ", ambient)?;
    writeln!(
        w,
        "      diffuseColor {} {} {}",
        r * diffuse,
        g * diffuse,
        b * diffuse
    )?;
    writeln!(
        w,
        "      specularColor {} {} {}",
        r * specular,
        g * specular,
        b * specular
    )?;
    writeln!(w, "      emissiveColor 0 0 0")?;
    writeln!(w, "      shininess {}", shininess)?;
    writeln!(w, "      transparency {}", obj.trans as f32 / 100.0)?;
    writeln!(w, "    }}")?;
    writeln!(w, "  }}")?;
    writeln!(w, "}}")?;
    Ok(())
}

fn print_object(
    model: &ImodModel,
    ob: usize,
    obj: &ImodObject,
    w: &mut impl Write,
    args: &Args,
    stats: &mut Stats,
) -> io::Result<()> {
    let obj_scattered = is_scat(obj.flags);
    let has_spheres = obj_scattered || obj.pdrawsize > 0
        || obj.contours.iter().any(|c| c.sizes.is_some());

    if !args.all_objects && is_off(obj.flags) {
        return Ok(());
    }

    print_material(obj, ob, w)?;

    let safe_name = vrml_safe_name(obj, ob);
    writeln!(w)?;
    writeln!(w, "#DATA FOR OBJECT {}:", ob + 1)?;
    writeln!(w, "DEF {} Transform {{", safe_name)?;
    writeln!(w, "  children [")?;

    if !obj_scattered && is_mesh_flag(obj.flags) {
        print_meshes(model, ob, obj, w, args, stats)?;
    }

    if has_spheres {
        print_scat_contours(model, ob, obj, w, args, stats)?;
    }

    writeln!(w, "  ]")?;
    writeln!(w, "}}")?;
    stats.num_objs += 1;
    Ok(())
}

fn point_size(obj: &ImodObject, cont: &ImodContour, p: usize) -> f32 {
    if let Some(ref sizes) = cont.sizes {
        if p < sizes.len() && sizes[p] > 0.0 {
            return sizes[p];
        }
    }
    if obj.pdrawsize > 0 {
        return obj.pdrawsize as f32;
    }
    0.0
}

fn print_scat_contours(
    model: &ImodModel,
    ob: usize,
    obj: &ImodObject,
    w: &mut impl Write,
    args: &Args,
    stats: &mut Stats,
) -> io::Result<()> {
    let safe_name = vrml_safe_name(obj, ob);
    let zscale = model.scale.z;

    writeln!(w, "    DEF obj{}_SPHERES Group {{    # GROUP OF POINTS:", ob + 1)?;
    writeln!(w, "      children [\n")?;

    for (c, cont) in obj.contours.iter().enumerate() {
        if cont.points.is_empty() {
            continue;
        }
        let has_sphere_sizes = is_scat(obj.flags) || obj.pdrawsize > 0 || cont.sizes.is_some();
        if !has_sphere_sizes {
            continue;
        }
        for (p, pt) in cont.points.iter().enumerate() {
            let radius = point_size(obj, cont, p);
            if radius > 0.0 {
                writeln!(
                    w,
                    "        DEF obj{}_cont{}_pt{} Transform {{",
                    ob + 1,
                    c + 1,
                    p + 1
                )?;
                writeln!(
                    w,
                    "          translation {} {} {} ",
                    pt.x,
                    pt.y,
                    pt.z * zscale
                )?;
                if args.rotate {
                    writeln!(w, "          rotation 1 0 0 1.570796 ")?;
                }
                writeln!(w, "          children [ Shape {{")?;
                write!(w, "              appearance USE MAT_{}\n", safe_name)?;
                if args.no_geom_names {
                    writeln!(
                        w,
                        "              geometry Sphere {{ radius {} }} }} ]",
                        radius
                    )?;
                } else {
                    writeln!(
                        w,
                        "              geometry DEF cont{}_pt{} Sphere {{ radius {} }} }} ]",
                        c + 1,
                        p + 1,
                        radius
                    )?;
                }
                writeln!(w, "        }}")?;
                stats.num_spheres += 1;
            }
        }
    }

    writeln!(w, "      ]")?;
    writeln!(w, "    }}")?;
    Ok(())
}

fn print_mesh_points(
    mesh: &ImodMesh,
    zscale: f32,
    w: &mut impl Write,
    stats: &mut Stats,
) -> io::Result<()> {
    writeln!(w, "        coord Coordinate {{")?;
    writeln!(w, "          point [   # list of all points in mesh")?;
    // Vertices are interleaved: point, normal, point, normal...
    let mut i = 0;
    while i < mesh.vertices.len() {
        let v = &mesh.vertices[i];
        writeln!(w, "            {:.5} {:.5} {:.5},", v.x, v.y, v.z * zscale)?;
        stats.num_vertices += 1;
        i += 2; // skip normals
    }
    writeln!(w, "          ]")?;
    writeln!(w, "        }}")?;
    Ok(())
}

fn print_meshes(
    model: &ImodModel,
    ob: usize,
    obj: &ImodObject,
    w: &mut impl Write,
    args: &Args,
    stats: &mut Stats,
) -> io::Result<()> {
    let zscale = model.scale.z;
    let safe_name = vrml_safe_name(obj, ob);
    let obj_fill = is_fill(obj.flags);

    for mesh in &obj.meshes {
        if obj_fill {
            // IndexedFaceSet
            writeln!(w, "    Shape {{  #MESH ")?;
            write!(w, "      appearance USE MAT_{}\n", safe_name)?;
            if args.no_geom_names {
                writeln!(w, "      geometry IndexedFaceSet {{")?;
            } else {
                writeln!(
                    w,
                    "      geometry DEF obj{}_mesh1 IndexedFaceSet {{",
                    ob + 1
                )?;
            }
            writeln!(w, "        ccw FALSE ")?;
            writeln!(w, "        solid FALSE ")?;
            writeln!(w, "        creaseAngle 1.56207 ")?;

            print_mesh_points(mesh, zscale, w, stats)?;

            // Parse index list for triangles
            writeln!(w, "        coordIndex [   # connect triangles")?;
            let indices = &mesh.indices;
            let mut i = 0;
            while i < indices.len() {
                if indices[i] == IMOD_MESH_END {
                    break;
                }
                let (list_inc, vert_base) =
                    mesh_poly_norm_factors(indices[i]);
                if list_inc == 0 {
                    i += 1;
                    continue;
                }
                i += 1;
                while i < indices.len() && indices[i] != IMOD_MESH_ENDPOLY {
                    if i + 2 * list_inc as usize >= indices.len() {
                        break;
                    }
                    let i0 = indices[(i + vert_base as usize).min(indices.len() - 1)] / 2;
                    i += list_inc as usize;
                    let i1 = indices[(i + vert_base as usize).min(indices.len() - 1)] / 2;
                    i += list_inc as usize;
                    let i2 = indices[(i + vert_base as usize).min(indices.len() - 1)] / 2;
                    i += list_inc as usize;
                    writeln!(w, "          {},{},{},-1,", i2, i1, i0)?;
                    stats.num_faces += 1;
                }
                if i < indices.len() && indices[i] == IMOD_MESH_ENDPOLY {
                    i += 1;
                }
            }
            writeln!(w, "        ]")?;
            writeln!(w, "      }}")?;
            writeln!(w, "    }}")?;
        } else {
            // PointSet fallback
            writeln!(w, "    Shape {{")?;
            write!(w, "      appearance USE MAT_{}\n", safe_name)?;
            if args.no_geom_names {
                writeln!(w, "      geometry PointSet {{")?;
            } else {
                writeln!(
                    w,
                    "      geometry DEF obj{}_all_points PointSet {{",
                    ob + 1
                )?;
            }
            print_mesh_points(mesh, zscale, w, stats)?;
            writeln!(w, "      }}")?;
            writeln!(w, "    }}")?;
        }
    }

    // Contour lines
    if args.contours {
        for (c, cont) in obj.contours.iter().enumerate() {
            if cont.points.is_empty() {
                continue;
            }
            writeln!(w, "    Shape {{  #CONTOUR ")?;
            write!(w, "      appearance USE MAT_{}\n", safe_name)?;
            if args.no_geom_names {
                writeln!(w, "      geometry IndexedLineSet {{")?;
            } else {
                writeln!(
                    w,
                    "      geometry DEF obj{}_cont{} IndexedLineSet {{",
                    ob + 1,
                    c + 1
                )?;
            }
            writeln!(w, "        coord Coordinate {{")?;
            writeln!(w, "          point [   # contour points")?;
            for pt in &cont.points {
                writeln!(
                    w,
                    "            {:.5} {:.5} {:.5},",
                    pt.x,
                    pt.y,
                    pt.z * zscale
                )?;
                stats.num_vertices += 1;
            }
            writeln!(w, "          ]")?;
            writeln!(w, "        }}")?;
            writeln!(w, "        coordIndex [")?;
            write!(w, "          ")?;
            for p in 0..cont.points.len() {
                write!(w, "{},", p)?;
            }
            // Close contour if closed
            let cont_open = cont.flags & ICONT_OPEN != 0;
            if !cont_open {
                write!(w, "0")?;
            }
            writeln!(w)?;
            writeln!(w, "        ]")?;
            writeln!(w, "      }}")?;
            writeln!(w, "    }}")?;
        }
    }

    Ok(())
}

/// Determine iteration factors from a mesh polygon start command.
/// Returns (list_inc, vert_base). Returns (0, 0) for non-polygon-norm types.
fn mesh_poly_norm_factors(cmd: i32) -> (usize, usize) {
    match cmd {
        IMOD_MESH_BGNPOLYNORM => (2, 0),
        IMOD_MESH_BGNPOLYNORM2 => (1, 0),
        _ => (0, 0),
    }
}
